[build]
  publish = "dist"
  command = "npm run build"

# Block indexing on deploy previews and branch deploys
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
  # Only apply to deploy previews
  [headers.condition]
    not_domain = "healthinsurancecomparison.co.nz"

# Production domain - allow indexing
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"
  [headers.condition]
    domain = "healthinsurancecomparison.co.nz"

# Security headers for production
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
